include("/home/kowalski0805/UANLP/cuda_exe/cmake/CPM_0.40.0.cmake")
CPMAddPackage("NAME;GTest;VERSION;1.16.0;BUILD_STATIC;FIND_PACKAGE_ARGUMENTS;EXACT;GIT_REPOSITORY;https://github.com/google/googletest.git;GIT_TAG;v1.16.0;GIT_SHALLOW;ON;EXCLUDE_FROM_ALL;OFF;OPTIONS;INSTALL_GTEST OFF;CMAKE_POSITION_INDEPENDENT_CODE ON;BUILD_SHARED_LIBS OFF")
set(GTest_FOUND TRUE)