include("/home/kowalski0805/UANLP/cuda_exe/cmake/CPM_0.40.0.cmake")
CPMAddPackage("NAME;cudf;VERSION;25.04.00;GIT_REPOSITORY;https://github.com/rapidsai/cudf.git;GIT_TAG;branch-25.04;GIT_SHALLOW;TRUE;SOURCE_SUBDIR;cpp;OPTIONS;BUILD_TESTS OFF;BUILD_BENCHMARKS OFF;CUDF_USE_ARROW_STATIC ON;JITIFY_USE_CACHE ON;AUTO_DETECT_CUDA_ARCHITECTURES OFF;CUDF_KVIKIO_REMOTE_IO OFF")
set(cudf_FOUND TRUE)